spring:
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/vote
    username: postgres
    password: root
  jpa:
    show-sql: true
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true


feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: full
